### ISSUE TITLE
WatchOS Support

### ISSUE THREAD

**Issue by Narsail** [skreutzberger/SwiftyBeaver#16]
After some tries with Cocoapods (where it needs to be declared for a watchOS use) i decided to use carthage, added the frameworks to my project and it still won't work with my Watch Extension classes.

So this is a question and request:
- Can i use the framework at this state for the watch extension?

If not, please add support for the Watch Extension. :)

**Comment by skreutzberger** [comment]
It currently does not work with WatchOS but it should be relatively easy to add all missing targets (AppleTV OS, WatchOS, ...).

Anyone want to contribute?

**Comment by Narsail** [comment]
I tried it myself, didn't work out ^^ I guess it didn't work cause of my missing experience with actually building frameworks/releases -.-

**Comment by skreutzberger** [comment]
No problem, I am sure either I or someone else will figure it out very soon. In the meantime, please star the project and follow the new [dedicated Twitter account](https://twitter.com/SwiftyBeaver) to get informed when WatchOS support is coming. Thanks!

**Comment by skreutzberger** [comment]
We implemented support for all Apple platforms and all installation systems with v0.2.5, released some minutes ago. The commit is ac3b2571a1509cb0d
