### ISSUE TITLE
Swift Package Manager package

### ISSUE THREAD

**Issue by harlanhaskins** [skreutzberger/SwiftyBeaver#19]
There's been a good discussion on one of the the Swift mailing lists about a good logging framework. Any chance you could make a Package.swift file?

**Comment by skreutzberger** [comment]
Can you please post a link to that discussion here or send as Twitter DM to @SwiftyBeaver?

I already thought about making a Package.swift file but all that stuff is so new :)

Anyone with more experience on that topic willing to contribute? I would love if SwiftyBeaver could be installed via Apple’s new Package Manager.

**Comment by davidrothera** [comment]
At the moment it looks like you would need to change the layout of the repo to support the packages, all the source files need to be under `./sources/`

https://github.com/apple/swift-package-manager/blob/master/Documentation/SourceLayouts.md

**Comment by skreutzberger** [comment]
@davidrothera Do you want to dive into it (maybe because you are anyway interested in that topic) or should I do it? I love the concept of the Swift Package Manager and it would be fantastic to support it better sooner than later :+1:

**Comment by davidrothera** [comment]
I'll take a look today :+1:

**Comment by skreutzberger** [comment]
Awesome, thanks a lot!

**Comment by skreutzberger** [comment]
@harlanhaskins - we made it! Can you point us please to the discussion that you mentioned or maybe directly endorse SwiftyBeaver? Thanks!

**Comment by harlanhaskins** [comment]
Woo! This is great! The discussion is on the mailing lists, here: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20151130/000413.html

It'd probably be a good idea to make a general post as the owner of SwiftyBeaver on the swift-users mailing list announcing the SPM support.

Great job and great turnaround time!

**Comment by skreutzberger** [comment]
Thanks! I just sent an email to the mailing list, I hope it hit the right tone :wink:
