### ISSUE TITLE
It's not working for me 

### ISSUE THREAD

**Issue by chenyunguiMilook** [skreutzberger/SwiftyBeaver#3]
the console output is like this
[2015-12-01 14:25:13.784] ViewController.viewDidLoad():22 [fg255,255,0;WARNING[;: message

**Comment by skreutzberger** [comment]
What XCode version do you use? I had several people test it under Xcode 7.1 and it worked at everyone.

**Comment by chenyunguiMilook** [comment]
My Xcode version is 7.1.1(7B1005)
OS X version is 10.11.1 Beta(15C48a)

**Comment by skreutzberger** [comment]
It seems the escape character `\u{001b}` which comes before every color and the reset color is not correctly displayed. I mean the value from the line https://github.com/skreutzberger/SwiftyBeaver/blob/master/SwiftyBeaver/SwiftyBeaver.swift#L51

Can you try to run the following lines? It should print your console in color:
```Swift
let escape = "\u{001b}"
let blue = "[fg0,0,255;"
let reset = "\u{001b}[0m"
let str = escape + blue + "I am blue" + reset
print(str)
```

**Comment by chenyunguiMilook** [comment]
still not working, the result is like below: 
[fg0,0,255;I am blue[0m

**Comment by chenyunguiMilook** [comment]
<img width="205" alt="2015-12-01 4 17 06" src="https://cloud.githubusercontent.com/assets/11513291/11495547/01cbae7c-9847-11e5-9391-6bca17af3d5f.png">

**Comment by skreutzberger** [comment]
Alright, it seems your Xcode still requires the [Xcode-Colors](https://github.com/robbiehanson/XcodeColors). I already have a built version which should work for you, too.

Please do the following:
1. Download the file [XcodeColors.xcplugin.zip](https://github.com/skreutzberger/SwiftyBeaver/raw/master/Assets/XcodeColors.xcplugin.zip)
2. Unzip it to "~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/"
3. Restart Xcode, allow the plugin

**Comment by chenyunguiMilook** [comment]
Thanks, now it's working for me, this is the result 
<img width="105" alt="2015-12-01 4 47 44" src="https://cloud.githubusercontent.com/assets/11513291/11496212/5f192934-984b-11e5-8568-6894f9d75a57.png">
