### ISSUE TITLE
Format of string in console.

### ISSUE THREAD

**Issue by hunk** [skreutzberger/SwiftyBeaver#35]
Hi, i have a little problem with the format output in console. this is my output.

```
[2015-12-10 14:44:59.071] AppDelegate.application(_:didFinishLaunchingWithOptions:):24 [fg200,200,200;VERBOSE[;: Nothing really happened
```
i have installed XcodeColors and use the las version of SwiftyBeaver (Manually)

**Comment by davidrothera** [comment]
That looks like XcodeColors is not working. Can you reinstall the latest version of it and try again.

**Comment by hunk** [comment]
Thanks, yes, some happen with XcodeColors colors
