### ISSUE TITLE
Injectable log destinations

### ISSUE THREAD

**Issue by vittoriom** [skreutzberger/SwiftyBeaver#8]
I saw that you have pretty hard-coded handlers for console and file destinations, but:

1- It's not flexible enough
2- It's not scalable

What if I want to have a Bonjour destination or a remote HTTP endpoint one? 
It could be nice to setup a logger to log to multiple configured destinations (even multiple files, for example)

**Comment by skreutzberger** [comment]
That would mean a lot of refactoring but your idea makes more than sense and it would be great to have it. I don’t have a quick solution how to do it elegantly and flexibly so maybe it is something worth contributing?! :wink:

**Comment by vittoriom** [comment]
Sure, I'd love to do it. 
Unfortunately I don't have enough free time lately, since I'm starting to work on a personal project + I have enough features to work on for my [Carlos](https://github.com/WeltN24/Carlos) repo as well :crying_cat_face: 
let's see if someone else can step in!

**Comment by skreutzberger** [comment]
Carlos looks nice, I will look deeper into that, too. But before doing that: SwiftyBeaver needs some flexible tails :smile:  - or teeth?

**Comment by skreutzberger** [comment]
Implemented & released at 3ccc67c
