### ISSUE TITLE
Add CocoaPods Support

### ISSUE THREAD

**Issue by skreutzberger** [skreutzberger/SwiftyBeaver#9]
Like the title says :smile:

**Comment by davidrothera** [comment]
Happy to help with this, the only issue changing to CocoaPods is that the layout of the project will change quite a bit.

If you are ok with that I will submit a PR :smile:

**Comment by skreutzberger** [comment]
Would it make other things much harder? Or is Cocoapods anyway already declining due to Carthage and the soon released package manager by Apple?

**Comment by davidrothera** [comment]
I think CocoaPods is going to be around for quite some time now to be honest.

It's not that it makes building or testing any harder, it is just a different layout in the directory.

I will put up a branch on my fork showing what it would look like now.

**Comment by skreutzberger** [comment]
perfect, thanks a lot!  

FYI: I just finished issues #10 #11 and #12 and will push the changes in some minutes.
